version: '3.8'

services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root1234!!
      MYSQL_DATABASE: keynote
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"

  app:
    image: eotaegyu/keynote.app
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/keynote?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root1234!!
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  db-data:
